import { makeStyles } from "@material-ui/core/styles";
export default makeStyles((theme) => ({
  root: {
    marginLeft: "30px",
    marginRight: "30px",
    marginTop: "10px",
  },
  topRightDiv: {
    position: "absolute",
    top: "68px",
    right: "0",
  },
  infoDiv: {
    backgroundColor: "#5589D8",
    borderRadius: "10px",
    width: "182px",
    height: "100px",
    float: "left",
    padding: "11px",
    marginLeft: "10px",
  },
  infoIcon: {
    width: "105px",
    height: "70px",
    color: "white",
    marginTop: "15px",
    marginLeft: "-10px",
    float: "left",
  },
  infoTitle: {
    color: "white",
    fontSize: "70px",
    margin: "0px",
    marginTop: "-3px",
  },
  infoSubtitle: {
    color: "white",
    fontSize: "22px",
    margin: "0px",
    marginTop: "-10px",
  },
  btnP: {
    fontSize: "25px",
    color: "white",
    display: "table-cell",
    verticalAlign: "middle",
    textAlign: "center",
  },
  btnDiv: {
    borderRadius: "5px",
    display: "table",
    cursor: "pointer",
  },
  btnStoreAnalytics: {
    float: "left",
    height: "132px",
    width: "141px",
    backgroundColor: "#5589D8",
    marginLeft: "50px",
  },
  btnDeactivateQueue: {
    height: "63px",
    width: "246px",
    backgroundColor: "#E86B30",
    marginBottom: "4px",
    marginLeft: "2px",
  },
  btnEmptyQueue: {
    height: "63px",
    width: "246px",
    backgroundColor: "#F5CC00",
    marginLeft: "2px",
    marginRight: "30px",
  },
  btnCustomerExited: {
    height: "47px",
    width: "230px",
    clear: "both",
    backgroundColor: "#5589D8",
    marginTop: "-10px",
  },
  recentSectionTitle: {
    fontSize: "37px",
    color: "#4455BB",
    marginTop: "60px",
    marginBottom: "10px",
  },
  recentSection: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  recentTitle: {
    fontSize: "30px",
    marginLeft: "93px",
  },
  undo: {
    height: "50px",
    width: "180px",
    backgroundColor: "#F5CC00",
    marginRight: "50px",
  },
  currentWaitingTitleBox: {
    display: "flex",
    justifyContent: "flex-start",
    alignItems: "center",
  },
  currentSectionTitle: {
    fontSize: "37px",
  },
  btnSendAnnouncement: {
    height: "50px",
    width: "275px",
    backgroundColor: "#5589D8",
    marginLeft: "30px",
  },
  currentSection: {},
  currentMember: {
    height: "100px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  currentNumber: {
    fontSize: "58px",
    marginLeft: "30px",
  },
  currentLeftStuff: {
    display: "flex",
    justifyContent: "flex-start",
    alignItems: "center",
  },
  currentInfo: {
    marginLeft: "30px",
  },
  currentTitle: {
    fontSize: "30px",
    margin: "0px",
  },
  currentSubtitle: {
    fontSize: "18px",
    margin: "0px",
    opacity: 0.5,
    fontStyle: "italic",
  },
  currentRightStuff: {
    display: "flex",
    justifyContent: "flex-end",
    alignItems: "center",
  },
  btnScanQr: {
    height: "50px",
    width: "175px",
    backgroundColor: "#5589D8",
    marginRight: "20px",
  },
  btnAccept: {
    height: "50px",
    width: "175px",
    backgroundColor: "#A8E071",
    marginRight: "20px",
  },
  btnNotify: {
    height: "50px",
    width: "175px",
    backgroundColor: "#F5CC00",
    marginRight: "20px",
  },
  btnReject: {
    height: "50px",
    width: "175px",
    backgroundColor: "#E86B30",
    marginRight: "20px",
  },
}));
